name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    runs-on: macos-14
    strategy:
      matrix:
        swift-version: ['6.1']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
    
    - name: Swift Version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v

  test-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:6.1
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Swift Version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v

  package-validation:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
    
    - name: Validate Package
      run: swift package dump-package
    
    - name: Check Package Dependencies
      run: swift package show-dependencies
    
